// CREATE USER
POST http://localhost:9000/books
Content-Type: application/json

{
    "name": "Candil",
    "year": "dsadas ",
    "author": "Kolak Candil",
    "summary": "Lorem Dolor sit Amet",
    "publisher": "Dicoding",
    "pageCount": 200,
    "readPage": 200,
    "reading": false
}

### 
PUT  http://localhost:9000/books/asaWJS
Content-Type: application/json

{
    "name": "ipang",
    "year": "dsadas ",
    "author": "ipang",
    "summary": "Lorem Dolor sit Amet",
    "publisher": "Dicoding",
    "pageCount": 200,
    "readPage": 200,
    "reading": false
}
###
GET http://localhost:9000


###
GET http://localhost:9000/books/dU2l0iTx60R-wVZQuHWJS
// LOGIN
### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "ipang@admin.com",
    "password" : "admin"

}

// ME
###
GET http://localhost:3000/me


###
DELETE http://localhost:3000/logout

